apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-user: user # required field for kubernetes.io/basic-auth
  postgres-password: password # required field for kubernetes.io/basic-auth